# Theme Configuration
remote_theme: pages-themes/minimal@v0.2.0
#theme: minimal-mistakes-jekyll

# Site Title & Description
title: ğŸ Python ğŸ
description: ğŸ‘»ğŸ•¯ğŸƒğŸ•¸ Happy Halloween ğŸ‘»ğŸ•¯ğŸƒğŸ•¸
timezone: America/New_York
lang: en-US

# Color Customization 
color_scheme: dark

# Navigation Structure TODO: structure main tree
main_nav:
  - title: "Home"
    url: /

# Author Information
author:
  name: Lila James
  email: ljames@riverdale.edu
  #twitter: your_twitter_handle
  github: https://github.com/kyle1james
  #linkedin: your_linkedin_username


# SEO & Feed (TODO: implement jekyll-seo-tag & jekyll-feed plugins)
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-responsive-image
  - jekyll-html-minify
  - jekyll-remote-theme
  
# If you have code blocks, enable line numbers for better clarity.
highlighter: rouge
line_numbers: true

# Google Analytics (if your theme supports it)
#google_analytics: UA-XXXXXXX
